### ISSUE TITLE
Help Needed: Accessing Child Widget from gtk.FlowBoxChild Causes Panic

### ISSUE THREAD

**Issue by itsManjeet** [diamondburned/gotk4#153]
**Description:**

I'm working with GTK4 bindings in Go and have encountered a panic when trying to access a custom child widget from `gtk.FlowBoxChild`.

I created a subclass as per the instructions in [Subclassing](https://github.com/diamondburned/gotk4/issues/22) with the following structure:

```go
type ChildWidget struct {
    gtk.Widget
    // Other fields...
}

var childWidgetType = glib.RegisterSubclass[*ChildWidget]()
```

I attempted to access this `ChildWidget` within a `FlowBox` like so:

```go
flowBox.ConnectChildActivated(func(child *gtk.FlowBoxChild) {
    childWidget := child.Child().(*ChildWidget)
})
```

However, I encountered the following panic:

```
panic: interface conversion: gtk.Widgetter is *gtk.Widget, not *disk_card.DiskCard [recovered]
        panic: closure error: unexpected panic caught: interface conversion: gtk.Widgetter is *gtk.Widget, not *disk_card.DiskCard
```

**Expected Behavior:**

I expected to successfully cast `child.Child()` to my custom `ChildWidget` type without causing a panic.

**Actual Behavior:**

The application panics with the error mentioned above, indicating a type mismatch during the conversion.

**Steps to Reproduce:**

1. Create a subclass of `gtk.Widget` as shown.
2. Add instances of this subclass to a `FlowBox`.
3. Attempt to access and cast the child widget within the `ConnectChildActivated` callback.

**Environment:**

- Go version: `1.21.1`
- GTK version: `4.14.4`
- `gotk4` version: `v0.3.1`

**Additional Information:**

Any guidance on correctly accessing the child widget in this context would be greatly appreciated!

**Comment by diamondburned** [comment]
Subclassing currently barely works and will very likely be removed in the future in order to allow development on dynamic runtime linking. Sorry about this.

**Comment by DeedleFake** [comment]
Sorry to post in an old issue, but I've run into this myself recently in a particularly awkward situation. Is there a good workaround for this kind of situation? I have some extra data that I need to get access to in a field in the subclass.

Specifically, I've got an `adw.ViewStack` hooked up to a `gtk.ListBox` by binding its pages model through an intermediary `gtk.SortListModel`. The problem is that the handler for changing the stack page when a row is selected doesn't work because the indices don't match thanks to the sorting. My thought was to use a custom row that could keep track of what page it was tied to, but I can't actually get access to it because of this problem.

Edit: And I figured out a solution. I guess I just needed to write it down or something. It seems kind of obvious in retrospect. I just needed one extra level of indirection. The handler wound up looking like this:

```go
win.PeersList.ConnectRowSelected(func(row *gtk.ListBoxRow) {
	if row == nil {
		return
	}

	page := win.PeersSortModel.Item(uint(row.Index())).Cast().(*adw.ViewStackPage)
	win.PeersStack.SetVisibleChildName(page.Name())
})
```
